# Numpy Basic

### Characteristic of Numpy

Numpy 
+ is faster than python normal list and efficient for memory.
+ supports process of array without iteration.
+ supports function about linear algebra.
+ intergrates C, C++, Fortran.

### import

In [1]:
import numpy as np

+ Basically, we call numpy library as np. It's alias and sort of rule.

### Array creation

+ Numpy creates array with the `np.array` function.
+ Numpy can contain only one data type.(python list can contain many types.)
+ Numpy creates array using C language array.

<img src="./nb_images/numpy_list.png" alt="Drawing" style="width: 500px;"/>

In [4]:
test_array = np.array([1,4,5,8], np.float32)
print(test_array)
type(test_array[0])

[ 1.  4.  5.  8.]


numpy.float32

Data type is automatically converted.

In [11]:
test_array = np.array(["1", "4", 5, 8], np.float32) 
print(test_array)
print(type(test_array)) # array type
print(test_array.dtype) # data type
print(test_array.shape) # shape

[ 1.  4.  5.  8.]
<class 'numpy.ndarray'>
float32
(4,)


What is the shape of (4,) ?
- 1-dimension vector containing 4 element. It can be column/row vector.

On the other hand, from 2-dimnesion array or, matrix has row/column shape.

For your information,
- 1d array : vector
- 2d array : matrix
- greater than 2d array : tensor

In [15]:
test_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]], np.float32)
print(test_matrix)
print(test_matrix.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
(3, 3)


### Array shape - ndim & size

+ ndim - the number of dimension
+ size - the number of data
+ shape - tensor's shape (row/column etc.)

In [19]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]]])

print("ndim : ", tensor.ndim)
print("size : ", tensor.size)
print("shape : ", tensor.shape)

ndim :  3
size :  27
shape :  (3, 3, 3)
